platform :ios, '10.0'
inhibit_all_warnings!
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] ='10.0'
    end
  end
end

def commonPods
  pod 'AFNetworking'
  pod ''
  pod 'IQKeyboardManager','6.0.6'
  pod 'SDWebImage','4.4.3'
  pod 'SDCycleScrollView','1.75'
  pod 'Somo','0.8.0'
  end

target 'RFriend' do
  commonPods
end
